# Site settings
title: Embodying Code
email: akaye@saic.edu
description: >
  This course examines the possibilities of artistic form provided by modern computer-aided design
  and manufacturing technologies. Students will learn software-based tools such as Rhino3D,
  a computer aided design (CAD) package, as well as Grasshopper, a graphical algorithm editor
  tightly integrated with Rhino's modeling tools. Together, these tools afford a powerful modeling
  environment allowing students to explore generative algorithms, parametric design and the geometric
  interpretation of data and real-time interactions in the context of creating physical objects.
  Students will use laser cutters, 3D printers and CNC mills to give these geometric explorations physical form.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://embodyingcode.com" # the base hostname & protocol for your site
twitter_username: notandrewkaye
github_username:  notandrewkaye

# Build settings
markdown: kramdown
